### ISSUE TITLE
I try to connect but I get an error.

### ISSUE THREAD

**Issue by MFGxD** [joffnerd/botw-trainer#113]
So I did everything, I enter my Wii U's ip and then press connect but then it gives me this error.
Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadDataBufferSize()
   at BotwTrainer.Gecko..ctor(TcpConn tcpConn, MainWindow mainWindow)
   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

**Comment by joffnerd** [comment]
Are you using this tcp gecko

https://github.com/BullyWiiPlaza/tcpgecko
