### ISSUE TITLE
Crash on connect

### ISSUE THREAD

**Issue by InkDragon** [joffnerd/botw-trainer#126]
I just recently started getting a game crash when attempting to connect the trainer.

Error from the Wii U:
![photo_2017-05-02_18-13-44](https://cloud.githubusercontent.com/assets/3854603/25641629/1d814550-2f63-11e7-9eeb-5eb40d059e7a.jpg)

Error Data from the trainer:
Error data will appear here
Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetUInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: source   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at BotwTrainer.Gecko.GetString(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: source   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at BotwTrainer.Gecko.GetString(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetUInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetFloat(UInt32 address)

**Comment by Frodil** [comment]
I'm getting the same, but I believe it's due to the game updating after the dlc announcement, because the same happened last time the game updated...

**Comment by InkDragon** [comment]
Good to know, I can only hope so.
