### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pchard** [joffnerd/botw-trainer#147]
Error while connecting:

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetUInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: source   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at BotwTrainer.Gecko.GetString(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: source   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at BotwTrainer.Gecko.GetString(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetUInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetFloat(UInt32 address)

**Comment by Tarog** [comment]
I think the trainer is dead he isnt working on it anymore since may i believe

**Comment by skoolzout1** [comment]
We're working on it.

**Comment by chariram123** [comment]
@shoolzout1 your working on the trainer? I am stuck in master mode and I want to use the trainer to help me

**Comment by joffnerd** [comment]
Updated for 1.3
