### ISSUE TITLE
Game Crashes (as of 1.3.1 update)

### ISSUE THREAD

**Issue by Randomizzerr** [joffnerd/botw-trainer#168]
My Wii U is on 5.5.2, Zelda BToW (USA) is on 1.3.1 and the trainer is on the latest version of 4.1.5. The game crashes as soon as I press 'connect'. The game is in master mode. I'm 99.99% sure it's crashing because of the update from 1.3.0 to 1.3.1 but I've included the error log just in case as well as a link to a picture of the wii u's crash handler: http://imgur.com/A4One39

Error data will appear here
Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: source   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at BotwTrainer.Gecko.GetString(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetUInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetUInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: source   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at BotwTrainer.Gecko.GetString(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetUInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetUInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetFloat(UInt32 address)

**Comment by teuf504** [comment]
Same for me

**Comment by Draky50110** [comment]
Here, trainer is not crashing, it is the Wii U which crashes :(

Firm 5.5.2 + Haxchi + TCPGecko (last with codehandler) + Zelda 1.3.1 EUR.

Pressing on "Connect" crashes.

I took a photo to show the memory dump on TV.

![img_20170817_133523](https://user-images.githubusercontent.com/1558487/29410650-c90b3e2a-8351-11e7-9b39-220d725a0729.jpg)

**Comment by MattDemers** [comment]
I got the same error as @Draky50110 on Zelda 1.3.1 USA disk. Firm 5.5.2 + Haxchi + TCPGecko (last with codehandler)

**Comment by joffnerd** [comment]
Of course you will get n error, at the time the trainer was for 1.3.0
