### ISSUE TITLE
Items don't appear when I click load items. 

### ISSUE THREAD

**Issue by DaneMacFadden** [joffnerd/botw-trainer#209]
Also getting this error:

Could not load file or assembly 'YamlDotNet, Version=4.2.3.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e' or one of its dependencies. The system cannot find the file specified.   at BotwTrainer.Offsets.LoadOffsets()
   at BotwTrainer.MainWindow.LoadOffsets()
   at BotwTrainer.MainWindow.MainWindowLoaded(Object sender, RoutedEventArgs e)

Object reference not set to an instance of an object.   at BotwTrainer.MainWindow.get_VersionedItemOffsets()
   at BotwTrainer.MainWindow.LoadItemData()

**Comment by joffnerd** [comment]
Try 4.3.1 which includes yaml dll

**Comment by Ethereal-Impulse** [comment]
I tried 4.3.1, no more error log messages for me at least, but still no items are found. However, I can still change the time of day and teleport to specified coordinates (I could also do this on 4.3.0)

**Comment by joffnerd** [comment]
DLC is Required to use the Weapon/Armour Editors

**Comment by Ethereal-Impulse** [comment]
Oh I see! Both DLC, or just one of the two?
