### ISSUE TITLE
Crash upon using ANY codes. This is the error shown in the error tab.

### ISSUE THREAD

**Issue by Sapphireflames** [joffnerd/botw-trainer#29]
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()
   at BotwTrainer.MainWindow.SaveClick(Object sender, RoutedEventArgs e)

**Comment by rEd2k** [comment]
Sapphireflames at what point in the game did you start using the trainer? At the very start of the game, or some time later/further into game play? Also, did you ever use a mix of trainers and save your progress editing with each different one at different times ect? I have used two different kinds myself the one from here, and this one as well: https://gbatemp.net/threads/the-legend-of-zelda-breath-of-the-wild-trainer-eshop-eu-beta.463066/

I'm wondering by using either trainer and saving and progressing may have played a part in my crashes I'm having, and I'm also curious if the problem maybe only affects people that progress further in to the game and start seeing the crashes just like what happened to me.

**Comment by joffnerd** [comment]
New version which should help identify where exactly this happens

**Comment by Sapphireflames** [comment]
I'm currently using the trainer quite late into the game. I updated to the
v33 patch and stopped using the beta trainer after the fourth beast because
I wanted access to more slots in my inventory.

Btw totally unrelated but have you noticed freezing when you try to send a
code or edit memory in JgeckoU? It freezes the program for me.

Trainers work...ish for me though.

I'll try your new update and report back =3

**Comment by Sapphireflames** [comment]
Also, if you can get access to the health code from the beta trainer, it
actually works for me. Maybe add it as an "alternative method' if you'd
like to and are able.

**Comment by Sapphireflames** [comment]
Alright, latest version tested and it still crashes upon code use. 

Item editing is more stable however. =)

**Comment by joffnerd** [comment]
I need the error tab data please and a screenshot of your codes tab

ta

**Comment by Sapphireflames** [comment]
![1](https://cloud.githubusercontent.com/assets/20076542/23853424/6b8bc7b2-07e4-11e7-8b80-427b3bbf485a.PNG)
![2](https://cloud.githubusercontent.com/assets/20076542/23853425/6bb73c44-07e4-11e7-9936-d866e9e733ef.PNG)

**Comment by joffnerd** [comment]
Thanks, can you try https://github.com/joffnerd/botw-trainer/releases/tag/v2.5.1

Its saying shield slots but your values look fine. This new version should list more than 1 error if there are any.

**Comment by Sapphireflames** [comment]
Set Cheats
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.poke(UInt32 address, UInt32 value)
   at BotwTrainer.MainWindow.SetCheats(ICollection`1 cheats)

Stamina Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Health Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Rupee Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Mon Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Run Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Speed Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Weapon Slot Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Bow Slot Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Shield Slot Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

![3](https://cloud.githubusercontent.com/assets/20076542/23854954/b9661652-07eb-11e7-8389-37d7e5515667.PNG)

**Comment by Sapphireflames** [comment]
I hope this helps ^^'

**Comment by joffnerd** [comment]
Hmm, how do you use tcpgecko?

Can you use  the files  from  here  on your sd card please:

https://github.com/BullyWiiPlaza/Gecko-U-Updater

**Comment by Sapphireflames** [comment]
I use that daily. I place the new files onto the card and run the installer using the "X" cosmo installation on the WiiU. I always hope it'll make a difference but it seems my WiiU is cursed. 

I've reinstalled BOTW and the update loads of times because I thought it might be a file access problem, but it seems to just not work.

To update TCPGecko&Cosmo on the WiiU I just have to rerun the installer with the updated files on the SD Card right?

**Comment by joffnerd** [comment]
Once files are  copied to the sd card you just run tcp gecko app from homebrew channel and press X

**Comment by Sapphireflames** [comment]
Yeah, I thought that would be it. Unfortunately that means I'm doing everything I should be but it's simply not working =(

Very sad panda.
![maxresdefault](https://cloud.githubusercontent.com/assets/20076542/23859119/832f3ece-07fa-11e7-90a1-723d0084d51c.jpg)

**Comment by joffnerd** [comment]
Hah yeah, the  exceptions that are happening are coming from the original files used in this  project https://github.com/Chadderz121/tcp-gecko-dotnet 

They are files that talk to the tcp gecko handler and  i guess they aren't perfect. It's basically something i have no idea about because i didn't write that code :(

**Comment by Sapphireflames** [comment]
Well thanks for trying to help =3
At least you tried =)

**Comment by joffnerd** [comment]
No worries, JGecko U also freeze right? I think you have  some  sort of other issue here like network related.

**Comment by Sapphireflames** [comment]
Maybe, and yeah, it totally freezes

**Comment by xNeptune** [comment]
I've had this same issue whenever I try to use any of the cheats from the code tab. You aren't alone sad panda ;P If I manage to find something that fixes this I'll let you know :)

**Comment by joffnerd** [comment]
I think its something to do with your connection. The codes tab uses the cheat handler from cosmo cortney just like jgecko u. Its just basic ram writes.

**Comment by joffnerd** [comment]
Can you test this please:

https://joffnerd.s3.amazonaws.com/app.publish.test.zip

**Comment by Sapphireflames** [comment]
Back to test your latest:

  Problem Event Name:	CLR20r3
  Problem Signature 01:	BotwTrainer.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	58cc2ab6
  Problem Signature 04:	System
  Problem Signature 05:	4.6.1590.0
  Problem Signature 06:	5787eed5
  Problem Signature 07:	1fee
  Problem Signature 08:	17
  Problem Signature 09:	System.IO.IOException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	2057
  Additional Information 1:	8bd0
  Additional Information 2:	8bd038acb694ad1c5ea59440378be7ab
  Additional Information 3:	ca4b
  Additional Information 4:	ca4bbab8c5192cc24b1deb94d3a75731

**Comment by Sapphireflames** [comment]
Using requested version:
Set Cheats
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.poke(UInt32 address, UInt32 value)
   at BotwTrainer.MainWindow.SetCheats(ICollection`1 cheats)

**Comment by joffnerd** [comment]
You are using an old version. I removed TCPGecko and poke

**Comment by Sapphireflames** [comment]
I tried your latest and posted the crash upon hitting Test

**Comment by joffnerd** [comment]
Where did you post it?

**Comment by Sapphireflames** [comment]
Just above the old one.
It's not the error tab,  rather the windows error box because the
application crashed and didn't allow me to access the error box.

**Comment by joffnerd** [comment]
Check readme. Is your .Net up to date

**Comment by Sapphireflames** [comment]
Should be but I'll update and report back. =3
Might take an hour or so till I can get back on my pc

**Comment by EpicLPer** [comment]
Dayum that's a long hour.

**Comment by Sapphireflames** [comment]
Sure is. Had other things to take care of.  =)

**Comment by windygeko** [comment]
So whenever I try to run the trainer, I get this for an error code, also the WII U literally does a "stack dump" death screen, heres the error what can I do?

Error data will appear here
Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetUInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: source   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at BotwTrainer.Gecko.GetString(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: source   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at BotwTrainer.Gecko.GetString(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetUInt(UInt32 address)

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.RequestBytes(UInt32 address, UInt32 length)

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

Value cannot be null.
Parameter name: array   at System.Array.Reverse(Array array)
   at BotwTrainer.Gecko.GetFloat(UInt32 address)
