### ISSUE TITLE
Tracking Coords is the only thing not working

### ISSUE THREAD

**Issue by Mr-Rixa** [joffnerd/botw-trainer#72]
Console: **PAL** 5.5.1
Game: PAL with latest patch
Trainer: v3.5 (test: server: 02/25/17, os: 550)
-

Checking tick for tracking coords gives an error and text `0x11BADF40 <- Memory Address` appears next to the tick box.

In Error Log is the following
```
Error data will appear here
Coords Tab
Input string was not in a correct format.   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToSingle(String value)
   at BotwTrainer.MainWindow.<>c__DisplayClass2d.<LoadCoords>b__27()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at BotwTrainer.MainWindow.LoadCoords()
```
Tried few different versions of trainer, but it made no difference.
Teleporting to coordinates does work and **everything else does work.**

**Comment by joffnerd** [comment]
Odd that it can't read the data since it must be correct as you can teleport.

**Comment by Mr-Rixa** [comment]
Indeed it's really odd. I decided to remove and fetch Gecko U again and now the problem is the same, but ~this time the text near the tick box says~.

So far I've got 
`0x11BADF40 <- Memory Address` 
`0x11BAE1C0 <- Memory Address` and
`0x11BAEBC0 <- Memory Address`
First I thought maybe starting game in gamepad or TV mode makes a difference, but apparently it doesn't and the Memory Address changes sometimes when you restart the game.

Here's a pic
![Image of the tick box](https://mr-rixa.fi/i/vl73o9.png)

The version I'm playing is the Eshop version if that makes a difference.

**Comment by joffnerd** [comment]
The memory address moves so it requires a pointer which is why I am printing in the tab in case you want to look it up in jgecko u

Can you go to the address it gives you in jgecko memory tab and  screenshot?

**Comment by Mr-Rixa** [comment]
Sure! 
`11BADF40 45501B41 436B516B 450DE79B 41F000F0`

Here you go
![Picture of jgecko](https://mr-rixa.fi/i/szc09y.png)

**Comment by joffnerd** [comment]
Does it still happen with this:

[test.publish.zip](https://github.com/joffnerd/botw-trainer/files/866210/test.publish.zip)

**Comment by Mr-Rixa** [comment]
Nice work! Works like a charm. Even the time changing works 😄  

![Pic of trainer](https://mr-rixa.fi/i/hs9k5w.png)
