### ISSUE TITLE
I keep getting this

### ISSUE THREAD

**Issue by cac289** [joffnerd/botw-trainer#80]
Not connected.   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.ReadDataBufferSize()
   at BotwTrainer.Gecko..ctor(TcpConn tcpConn, MainWindow mainWindow)
   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

**Comment by joffnerd** [comment]
You aren't using bullys tcp gecko. check the readme

**Comment by cac289** [comment]
I thought I was where do I put the files after I run it?

**Comment by joffnerd** [comment]
4 tcp gecko files go on your SD card which you then run from homebrew channel before starting the game

**Comment by joffnerd** [comment]
1 week old, closing
