### ISSUE TITLE
The trainer isn't responding 

### ISSUE THREAD

**Issue by ThingyMan** [joffnerd/botw-trainer#88]
When connecting to my wii u, the trainer just stops responding and nothing happens what can I do to fix this? I'm on PAL region btw.

**Comment by ThingyMan** [comment]
okay so now I found this:
at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
 at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.GetServerStatus()
   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

um what now?

**Comment by danne2** [comment]
The BOTW update (1.1.1) broke the trainer. You'll need to wait for it to be updated.

**Comment by ThingyMan** [comment]
ah k

**Comment by joffnerd** [comment]
Closing all issues which are probably related to 1.1.1
